# Generated by Django 4.2.4 on 2023-08-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predresults',
            name='petal_length',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='petal_width',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='sepal_length',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='sepal_width',
        ),
        migrations.AddField(
            model_name='predresults',
            name='client_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='predresults',
            name='dropoff_city_1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='predresults',
            name='dropoff_postcode_1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='predresults',
            name='number_pickups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predresults',
            name='number_shifts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predresults',
            name='number_trips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predresults',
            name='number_waits_returns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predresults',
            name='pickup_city_1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='predresults',
            name='pickup_postcode_1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='predresults',
            name='request_date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='predresults',
            name='start_date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='predresults',
            name='unsociable_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predresults',
            name='vehicle_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predresults',
            name='weekday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predresults',
            name='weekend',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='classification',
            field=models.FloatField(default=0),
        ),
    ]
