# Generated by Django 4.2.4 on 2023-08-13 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_remove_predresults_petal_length_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predresults',
            old_name='classification',
            new_name='pred_price',
        ),
    ]
