# Generated by Django 4.2.4 on 2023-08-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_rename_classification_predresults_pred_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='lower_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predresults',
            name='upper_price',
            field=models.FloatField(default=0),
        ),
    ]
